version: '3'
services:
  research:
    image: nvcr.io/nvidia/pytorch:21.12-py3
    volumes:
      - ./:/workspace
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    shm_size: '24gb'
